-- 内链
CREATE TABLE IF NOT EXISTS `bfchain_transactions`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `entity_id` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '唯一id',
  `chain_name` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '链名',
  `state` smallint(6) UNSIGNED NOT NULL DEFAULT 0 COMMENT '交易状态',
  `sender_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '发送者',
  `recipient_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '接收者',
  `type` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '事件类型',
  `signature` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '事件签名',
  `create_timestamp` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '事件创建时间戳',
  `apply_block_height` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '事件发起高度',
  `effective_block_height` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '事件失效高度，超过这个高度代表已失效',
  `onchain_timestamp` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '上链高度时间戳',
  `success_height` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '成功确认高度',
  `fail_height` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '失败确认高度',
  `retry_broadcast_num` smallint(6) UNSIGNED NOT NULL DEFAULT 0 COMMENT '重试广播次数',
  `link_type` tinyint(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '关联业务表类型',
  `link_id` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '关联业务表编号',
  `tr_json` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '交易体',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标志：0：正常，1：删除，默认0',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_entityId`(`entity_id`) USING BTREE COMMENT '唯一id索引',
  UNIQUE KEY `uniq_signature`(`signature`) USING BTREE COMMENT '事件签名索引',
  KEY `idx_state`(`state`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT = 'BFCHAIN交易信息表';

CREATE TABLE IF NOT EXISTS `bfmchain_transactions`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `entity_id` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '唯一id',
  `chain_name` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '链名',
  `state` smallint(6) UNSIGNED NOT NULL DEFAULT 0 COMMENT '交易状态',
  `sender_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '发送者',
  `recipient_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '接收者',
  `type` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '事件类型',
  `signature` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '事件签名',
  `create_timestamp` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '事件创建时间戳',
  `apply_block_height` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '事件发起高度',
  `effective_block_height` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '事件失效高度，超过这个高度代表已失效',
  `onchain_timestamp` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '上链高度时间戳',
  `success_height` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '成功确认高度',
  `fail_height` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '失败确认高度',
  `retry_broadcast_num` smallint(6) UNSIGNED NOT NULL DEFAULT 0 COMMENT '重试广播次数',
  `link_type` tinyint(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '关联业务表类型',
  `link_id` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '关联业务表编号',
  `tr_json` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '交易体',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标志：0：正常，1：删除，默认0',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_entityId`(`entity_id`) USING BTREE COMMENT '唯一id索引',
  UNIQUE KEY `uniq_signature`(`signature`) USING BTREE COMMENT '事件签名索引',
  KEY `idx_state`(`state`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT = 'BFM交易信息表';

CREATE TABLE IF NOT EXISTS `ccchain_transactions`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `entity_id` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '唯一id',
  `chain_name` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '链名',
  `state` smallint(6) UNSIGNED NOT NULL DEFAULT 0 COMMENT '交易状态',
  `sender_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '发送者',
  `recipient_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '接收者',
  `type` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '事件类型',
  `signature` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '事件签名',
  `create_timestamp` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '事件创建时间戳',
  `apply_block_height` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '事件发起高度',
  `effective_block_height` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '事件失效高度，超过这个高度代表已失效',
  `onchain_timestamp` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '上链高度时间戳',
  `success_height` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '成功确认高度',
  `fail_height` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '失败确认高度',
  `retry_broadcast_num` smallint(6) UNSIGNED NOT NULL DEFAULT 0 COMMENT '重试广播次数',
  `link_type` tinyint(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '关联业务表类型',
  `link_id` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '关联业务表编号',
  `tr_json` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '交易体',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标志：0：正常，1：删除，默认0',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_entityId`(`entity_id`) USING BTREE COMMENT '唯一id索引',
  UNIQUE KEY `uniq_signature`(`signature`) USING BTREE COMMENT '事件签名索引',
  KEY `idx_state`(`state`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT = 'CCC交易信息表';

CREATE TABLE IF NOT EXISTS `pmchain_transactions`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `entity_id` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '唯一id',
  `chain_name` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '链名',
  `state` smallint(6) UNSIGNED NOT NULL DEFAULT 0 COMMENT '交易状态',
  `sender_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '发送者',
  `recipient_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '接收者',
  `type` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '事件类型',
  `signature` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '事件签名',
  `create_timestamp` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '事件创建时间戳',
  `apply_block_height` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '事件发起高度',
  `effective_block_height` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '事件失效高度，超过这个高度代表已失效',
  `onchain_timestamp` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '上链高度时间戳',
  `success_height` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '成功确认高度',
  `fail_height` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '失败确认高度',
  `retry_broadcast_num` smallint(6) UNSIGNED NOT NULL DEFAULT 0 COMMENT '重试广播次数',
  `link_type` tinyint(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '关联业务表类型',
  `link_id` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '关联业务表编号',
  `tr_json` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '交易体',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标志：0：正常，1：删除，默认0',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_entityId`(`entity_id`) USING BTREE COMMENT '唯一id索引',
  UNIQUE KEY `uniq_signature`(`signature`) USING BTREE COMMENT '事件签名索引',
  KEY `idx_state`(`state`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT = 'PMC交易信息表';

CREATE TABLE IF NOT EXISTS `ethmeta_transactions`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `entity_id` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '唯一id',
  `chain_name` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '链名',
  `state` smallint(6) UNSIGNED NOT NULL DEFAULT 0 COMMENT '交易状态',
  `sender_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '发送者',
  `recipient_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '接收者',
  `type` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '事件类型',
  `signature` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '事件签名',
  `create_timestamp` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '事件创建时间戳',
  `apply_block_height` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '事件发起高度',
  `effective_block_height` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '事件失效高度，超过这个高度代表已失效',
  `onchain_timestamp` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '上链高度时间戳',
  `success_height` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '成功确认高度',
  `fail_height` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '失败确认高度',
  `retry_broadcast_num` smallint(6) UNSIGNED NOT NULL DEFAULT 0 COMMENT '重试广播次数',
  `link_type` tinyint(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '关联业务表类型',
  `link_id` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '关联业务表编号',
  `tr_json` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '交易体',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标志：0：正常，1：删除，默认0',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_entityId`(`entity_id`) USING BTREE COMMENT '唯一id索引',
  UNIQUE KEY `uniq_signature`(`signature`) USING BTREE COMMENT '事件签名索引',
  KEY `idx_state`(`state`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT = 'ETHM交易信息表';

-- 外链
CREATE TABLE IF NOT EXISTS `bsc_transactions`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `entity_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '唯一id',
  `chain_name` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '链名',
  `tx_hash` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '交易Hash',
  `from` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '交易发起地址',
  `to` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '交易接收地址',
  `value` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0' COMMENT '转账金额，以 wei 为单位',
  `asset_symbol` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '资产标识',
  `fee` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '手续费',
  `state` smallint(6) NOT NULL DEFAULT 0 COMMENT '交易状态',
  `tr_json` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '交易体',
  `nonce` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '交易序号',
  `link_type` tinyint(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '关联业务表类型',
  `link_id` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '关联业务表编号',
  `del_flag` tinyint(2) NOT NULL DEFAULT 0 COMMENT '逻辑删除标志：0：正常，1：删除，默认0',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_from_symbol`(`from`, `asset_symbol`) USING BTREE,
  KEY `idx_status`(`state`) USING BTREE,
  UNIQUE KEY `uniq_txHash`(`tx_hash`) USING BTREE,
  UNIQUE KEY `uniq_entityId`(`entity_id`) USING BTREE COMMENT '唯一id索引',
  KEY `idx_from_nonce`(`from`, `nonce`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT = 'BSC交易信息表';

CREATE TABLE IF NOT EXISTS `eth_transactions`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `entity_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '唯一id',
  `chain_name` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '链名',
  `tx_hash` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '交易Hash',
  `from` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '交易发起地址',
  `to` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '交易接收地址',
  `value` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0' COMMENT '转账金额，以 wei 为单位',
  `asset_symbol` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '资产标识',
  `fee` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '手续费',
  `state` smallint(6) NOT NULL DEFAULT 0 COMMENT '交易状态',
  `tr_json` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '交易体',
  `nonce` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '交易序号',
  `link_type` tinyint(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '关联业务表类型',
  `link_id` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '关联业务表编号',
  `del_flag` tinyint(2) NOT NULL DEFAULT 0 COMMENT '逻辑删除标志：0：正常，1：删除，默认0',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_from_symbol`(`from`, `asset_symbol`) USING BTREE,
  KEY `idx_status`(`state`) USING BTREE,
  UNIQUE KEY `uniq_txHash`(`tx_hash`) USING BTREE,
  UNIQUE KEY `uniq_entityId`(`entity_id`) USING BTREE COMMENT '唯一id索引',
  KEY `idx_from_nonce`(`from`, `nonce`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT = 'ETH交易信息表';

CREATE TABLE IF NOT EXISTS `tron_transactions`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `entity_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '唯一id',
  `chain_name` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '链名',
  `tx_hash` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '交易Hash',
  `from` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '发起地址',
  `to` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '接收地址',
  `value` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0' COMMENT '交易金额',
  `asset_symbol` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '资产标识',
  `state` smallint(6) NOT NULL DEFAULT 0 COMMENT '交易状态',
  `tr_json` varchar(5000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '交易体',
  `link_type` tinyint(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '关联业务表类型',
  `link_id` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '关联业务表编号',
  `del_flag` tinyint(2) NOT NULL DEFAULT 0 COMMENT '逻辑删除标志：0：正常，1：删除，默认0',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_from_symbol`(`from`, `asset_symbol`) USING BTREE,
  KEY `idx_status`(`state`) USING BTREE,
  UNIQUE KEY `uniq_txHash`(`tx_hash`) USING BTREE,
  UNIQUE KEY `uniq_entityId`(`entity_id`) USING BTREE COMMENT '唯一id索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT = 'TRON交易信息表';

-- 合约信息表
CREATE TABLE IF NOT EXISTS `contract_token_info`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `chain` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '归属链',
  `address` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '合约地址',
  `name` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '合约名称',
  `icon` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '合约图标url',
  `symbol` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '合约标识',
  `decimals` int(11) NOT NULL DEFAULT 1 COMMENT '合约精度',
  `total_supply` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0' COMMENT '发行总量',
  `website` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '网址',
  `publish_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发布时间',
  `del_flag` tinyint(2) NOT NULL DEFAULT 0 COMMENT '逻辑删除标志：0：正常，1：删除，默认0',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_chain`(`chain`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT = '合约代币信息表';

