CREATE TABLE IF NOT EXISTS `biwmeta_transactions` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
    `entity_id` varchar(50) NOT NULL DEFAULT '' COMMENT '唯一id',
    `chain_name` varchar(20) NOT NULL DEFAULT '' COMMENT '链名',
    `mq_id` varchar(255) NOT NULL DEFAULT '' COMMENT '消息队列id',
    `state` smallint(6) unsigned NOT NULL DEFAULT '0' COMMENT '交易状态',
    `sender_id` varchar(255) NOT NULL DEFAULT '' COMMENT '发送者',
    `recipient_id` varchar(255) NOT NULL DEFAULT '' COMMENT '接收者',
    `type` varchar(255) NOT NULL DEFAULT '' COMMENT '事件类型',
    `signature` varchar(255) NOT NULL DEFAULT '' COMMENT '事件签名',
    `create_timestamp` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '事件创建时间戳',
    `apply_block_height` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '事件发起高度',
    `effective_block_height` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '事件失效高度，超过这个高度代表已失效',
    `onchain_timestamp` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '上链高度时间戳',
    `success_height` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '成功确认高度',
    `fail_height` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '失败确认高度',
    `fail_reason` varchar(1000) NOT NULL DEFAULT '' COMMENT '失败原因',
    `retry_broadcast_num` smallint(6) unsigned NOT NULL DEFAULT '0' COMMENT '重试广播次数',
    `link_type` tinyint(4) unsigned NOT NULL DEFAULT '0' COMMENT '关联业务表类型',
    `link_id` varchar(50) NOT NULL DEFAULT '' COMMENT '关联业务表编号',
    `tr_json` text NOT NULL COMMENT '交易体',
    `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标志：0：正常，1：删除，默认0',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE KEY `uniq_entityId` (`entity_id`) USING BTREE COMMENT '唯一id索引',
    UNIQUE KEY `uniq_signature` (`signature`) USING BTREE COMMENT '事件签名索引',
    KEY `idx_state` (`state`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT = 'biwmeta交易信息表';